name: Setup cloudflared
description: Setup/Install Cloudflare Tunnel client for GitHub Actions
branding:
  icon: cloud
  color: orange
inputs:
  cloudflared-version:
    description: ""
    default: latest
runs:
  using: composite
  steps:
    - shell: bash
      run: '"$GITHUB_ACTION_PATH/main.sh"'
      env:
        INPUT_CLOUDFLARED_VERSION: ${{ inputs.cloudflared-version }}
